/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#344053",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#dbe4ea",
        "on-tertiary": "#fcf7ff",
        "secondary-dim": "#485467",
        "on-tertiary-fixed": "#3f3a54",
        "on-primary": "#f8f7ff",
        "on-error-container": "#752121",
        "error": "#9f403d",
        "outline-variant": "#aab3b9",
        "tertiary-container": "#e3dbfd",
        "error-container": "#fe8983",
        "inverse-primary": "#5c8bff",
        "on-secondary-container": "#465266",
        "primary-dim": "#004aba",
        "surface-tint": "#0c56d0",
        "secondary": "#546074",
        "on-primary-container": "#004ab9",
        "surface-dim": "#d1dce2",
        "on-tertiary-container": "#524c68",
        "on-surface": "#2b3438",
        "background": "#f8f9fb",
        "tertiary-fixed": "#e3dbfd",
        "outline": "#737c81",
        "tertiary-dim": "#554f6b",
        "surface-container-high": "#e2e9ee",
        "secondary-container": "#d7e3fb",
        "tertiary": "#615b77",
        "on-primary-fixed-variant": "#0253cd",
        "error-dim": "#4e0309",
        "inverse-surface": "#0c0f10",
        "on-tertiary-fixed-variant": "#5c5672",
        "secondary-fixed-dim": "#c9d5ed",
        "surface-bright": "#f8f9fb",
        "on-secondary-fixed-variant": "#505c70",
        "primary": "#0c56d0",
        "primary-container": "#dae2ff",
        "on-surface-variant": "#586065",
        "on-error": "#fff7f6",
        "tertiary-fixed-dim": "#d5cdee",
        "surface": "#f8f9fb",
        "surface-container-highest": "#dbe4ea",
        "surface-container-low": "#f1f4f7",
        "on-secondary": "#f8f8ff",
        "primary-fixed-dim": "#c6d3ff",
        "secondary-fixed": "#d7e3fb",
        "on-primary-fixed": "#003993",
        "primary-fixed": "#dae2ff",
        "on-background": "#2b3438",
        "surface-container": "#eaeef2",
        "inverse-on-surface": "#9b9d9f"
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
